config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/contact'
  get 'static_pages/about'
  get 'static_pages/news'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/marca.rb
class Marca < ApplicationRecord
    validates :name,        presence: true
    validates :description, presence: true
    validates :start,       presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def news
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	   <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BlackNeuron</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag %>
  </head>

  <body class="<%= controller.controller_name %>">
    <% if controller.action_name == 'hogar' %>
      <%= yield :home %>
    <% else %>
      <div class="topnav">
        <div id="banner">
          <%= image_tag("logoBNR.png", size: "150x50", alt: 'Black Neuron Research')  %>
        </div>
        <%= link_to 'Home', static_pages_home_path %>
        <%= link_to 'News', static_pages_news_path %>
        <%= link_to 'Contact', static_pages_contact_path %>
        <%= link_to 'About', static_pages_about_path %>
      </div>
        <div id="columns">
          <div id="side">
          </div>
          <div id="main">
            <%= yield %>
          </div>
        </div>
    <% end %>
    <footer>
        <small>BlackNeuron Research 2018</small>
    </footer>
    <div class="debug">
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="about-main">
  <h1>Software development is fun!</h1>
  <p>Black Neuron Research is a club to share experience and knowledge about web applications development
      using Ruby on Rails but open to any other technology. We want to expand our community to </p>
      <ul>
          <li>Technologists</li>
          <li>Thinkers</li>
          <li>Builders</li>
          <li>Designers</li>
      </ul>
  <p>working together to bring web development in central Mexico accessible and readily available, so people can be informed
      and up to date with web application development. Our aim is to help general public materialize their needs and ideas to the
      Internet.
  </p>
  <p>This is an ongoing effort and this page is in constant evolution, if you want to know more about our club, please <%= link_to  "contact us", static_pages_contact_path %></p>
</div>

app/views/static_pages/contact.html.erb
<div class="contact-main">
  <h1>Let's share a cup of hot tea!</h1>
  <p>We will be very happy to share a cup of hot tea while talking about your projects and aspirations, please send a message to <%= mail_to "fernando.flores1961@gmail.com", "fernando.flores1961@gmail.com", subject: "Let's have a cup of hot tea!" %></p>
</div>

app/views/static_pages/home.html.erb
<div class="hero-section">
  <div class="top-heading">
    <h1>A club for developers</h1>
  </div>
  <div class="bottom-heading">
    <h3>Coding with style, a learning playground</h3>
  </div>
</div>

app/views/static_pages/news.html.erb
<div class="grid-container">
    <div class="grid-item">
      <%= image_tag('RoR-logo.png', size: "80x100", alt: 'Ruby On Rails logo') %>
    </div>
    <div class="grid-item">
      <p>Próximo curso: Desarrollo en Ruby on Rails, desde instalación en plataformas Windows, Mac y Linux; Ruby on Rails 5.1; Desarrollo de aplicaciones Web en plataforma de producción Heroku, desarrollo de APIs para acceder con Angular y Ionic</p>
      <table>
        <tr>
          <th>Fecha</th>
          <th>Lugar</th>
          <th>Costo</th>
          <th>Cupo</th>
        </tr>
        <tr>
          <td>Sept. 20 2018</td>
          <td>Por definir</td>
          <td>$199 pesos por persona</td>
          <td>Máximo 5 personas</td>
        </tr>
      </table>
    </div>
    <div class="grid-item">
      <%= image_tag('processes.jpg', size: "80x100", alt: 'Business processes') %>
    </div>
    <div class="grid-item">
      <p>Proximamente: Curso de automatización de procesos de negocio, como definir los procesos de las aplicaciones y como definir y medir las métricas de desempeño de los procesos.</p>
    </div>
  </div>